"""
Code Generator - генерация рабочего Python-кода для ML-пайплайнов.

Genesis AI анализирует проект пользователя и генерирует готовый код:
- Загрузка и профилирование датасета
- Предобработка и очистка
- Обучение моделей (XGBoost, RandomForest, LogisticRegression)
- Кросс-валидация и метрики
- Сохранение модели
- Предсказание на новых данных
"""

import os
from typing import Dict, List, Any, Optional
from datetime import datetime


class CodeGenerator:
    """Генератор Python-кода для ML-задач."""
    
    def __init__(self, db=None):
        self.db = db  # GenesisDB instance
    
    def generate_from_project(self, project_name: str) -> str:
        """
        Генерирует полный ML-пайплайн по проекту пользователя.
        Использует данные из БД Genesis: проекты, датасеты, модели.
        """
        code = [
            self._header(project_name),
            self._imports(),
            self._load_data(project_name),
            self._profile_data(),
            self._preprocess(),
            self._train_models(),
            self._evaluate(),
            self._save_model(),
            self._predict_function(),
            self._main_block(project_name),
        ]
        return "\n\n".join(code)
    
    def generate_from_description(self, description: str) -> str:
        """
        Генерирует код по текстовому описанию задачи.
        Использует LLM для понимания задачи, затем собирает шаблон.
        """
        task_type = self._detect_task_type(description)
        target_hint = self._detect_target(description)
        
        code = [
            self._header("AutoML Pipeline"),
            self._imports(),
            f"# Task: {description}",
            f"# Auto-detected: {task_type}" + (f", target: {target_hint}" if target_hint else ""),
            self._load_data(),
            self._profile_data(),
            self._preprocess(),
            self._train_models(task_type),
            self._evaluate(task_type),
            self._save_model(),
            self._predict_function(),
            "# To run: python pipeline.py",
        ]
        return "\n\n".join(code)
    
    def _header(self, name: str) -> str:
        return f'''"""
{name} - AutoML Pipeline
Generated by Genesis AI on {datetime.now().strftime("%Y-%m-%d %H:%M")}
"""
'''
    
    def _imports(self) -> str:
        return '''import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.metrics import accuracy_score, f1_score, r2_score, mean_squared_error
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier, RandomForestRegressor
from xgboost import XGBClassifier, XGBRegressor
import pickle
from datetime import datetime
from datetime import datetime
from datetime import datetime
import warnings
warnings.filterwarnings("ignore")'''
    
    def _load_data(self, project_name: str = None) -> str:
        if project_name and self.db:
            projects = self.db.get_projects()
            for p in projects:
                if p.get('name') == project_name:
                    return f'''# Load dataset
# Project: {p.get('name')} ({p.get('task', 'unknown')})
df = pd.read_csv("datasets/{p.get('name', 'data').lower().replace(' ', '_')}.csv")
print(f"Loaded {{len(df)}} rows, {{len(df.columns)}} columns")
print(df.head())'''
        return '''# Load dataset
# Replace with your data path
df = pd.read_csv("datasets/churn_demo.csv")
print(f"Loaded {len(df)} rows, {len(df.columns)} columns")
print(df.head())'''
    
    def _profile_data(self) -> str:
        return '''# Profile dataset
print("\\n=== Dataset Profile ===")
print(f"Shape: {df.shape}")
print(f"\\nMissing values:\\n{df.isnull().sum()}")
print(f"\\nData types:\\n{df.dtypes}")
print(f"\\nBasic stats:\\n{df.describe()}")

# Auto-detect target column (last column)
target_col = df.columns[-1]
print(f"\\nTarget column: {target_col}")
print(f"Unique values: {df[target_col].nunique()}")
print(f"Value counts:\\n{df[target_col].value_counts()}")'''
    
    def _preprocess(self) -> str:
        return '''# Preprocessing
# Handle missing values
numeric_cols = df.select_dtypes(include=[np.number]).columns
categorical_cols = df.select_dtypes(exclude=[np.number]).columns

for col in numeric_cols:
    df[col] = df[col].fillna(df[col].median())

for col in categorical_cols:
    if col != target_col:
        df[col] = df[col].fillna(df[col].mode()[0] if len(df[col].mode()) > 0 else "Unknown")

# Encode categorical variables
le = LabelEncoder()
for col in categorical_cols:
    if col != target_col:
        df[col] = le.fit_transform(df[col].astype(str))

# Encode target if categorical
if df[target_col].dtype == 'object' or df[target_col].nunique() <= 10:
    df[target_col] = le.fit_transform(df[target_col].astype(str))

print("\\nPreprocessing complete")
print(f"Final shape: {df.shape}")'''
    
    def _train_models(self, task_type: str = None) -> str:
        # Определяем задачу по количеству уникальных значений
        return '''# Prepare features and target
X = df.drop(columns=[target_col])
y = df[target_col]

# Determine task type
if y.nunique() <= 2:
    task = "binary_classification"
    print("\\nTask: Binary Classification")
elif y.nunique() <= 50:
    task = "multiclass_classification"
    print("\\nTask: Multiclass Classification")
else:
    task = "regression"
    print("\\nTask: Regression")

# Split data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
print(f"Train: {len(X_train)}, Test: {len(X_test)}")

# Train models
models = {}

if "classification" in task:
    models["LogisticRegression"] = LogisticRegression(max_iter=1000, random_state=42)
    models["RandomForest"] = RandomForestClassifier(n_estimators=100, random_state=42)
    models["XGBoost"] = XGBClassifier(eval_metric="logloss", random_state=42, verbosity=0)
else:
    models["RandomForest"] = RandomForestRegressor(n_estimators=100, random_state=42)
    models["XGBoost"] = XGBRegressor(random_state=42, verbosity=0)

results = {}
for name, model in models.items():
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)
    results[name] = {"model": model, "predictions": y_pred}
    print(f"\\n{name} trained")'''
    
    def _evaluate(self, task_type: str = None) -> str:
        return '''# Evaluate models
print("\\n=== Model Evaluation ===")
best_model = None
best_score = 0

for name, res in results.items():
    y_pred = res["predictions"]
    if "classification" in task:
        acc = accuracy_score(y_test, y_pred)
        f1 = f1_score(y_test, y_pred, average="weighted")
        cv_scores = cross_val_score(res["model"], X, y, cv=min(5, len(X)//2), scoring="accuracy")
        print(f"{name}: Accuracy={acc:.4f}, F1={f1:.4f}, CV={cv_scores.mean():.4f}±{cv_scores.std():.4f}")
        if acc > best_score:
            best_score = acc
            best_model = (name, res["model"])
    else:
        r2 = r2_score(y_test, y_pred)
        rmse = np.sqrt(mean_squared_error(y_test, y_pred))
        print(f"{name}: R²={r2:.4f}, RMSE={rmse:.2f}")
        if r2 > best_score:
            best_score = r2
            best_model = (name, res["model"])

print(f"\\nBest model: {best_model[0]} (score: {best_score:.4f})")'''
    
    def _save_model(self) -> str:
        return '''# Save best model
model_path = "models/best_model_" + datetime.now().strftime('%Y%m%d_%H%M%S') + '.pkl'
with open(model_path, "wb") as f:
    pickle.dump(best_model[1], f)
print(f"\\nModel saved to {model_path}")

# Save feature names
feature_names = list(X.columns)
with open("models/feature_names.txt", "w") as f:
    f.write(",".join(feature_names))
print(f"Features: {feature_names}")'''
    
    def _predict_function(self) -> str:
        return '''# Prediction function
def predict(new_data: list) -> int:
    """
    Make prediction on new data.
    Args:
        new_data: list of feature values in order: {feature_names}
    Returns:
        prediction
    """
    import numpy as np
    features = np.array(new_data).reshape(1, -1)
    prediction = best_model[1].predict(features)
    return int(prediction[0])

# Example prediction
sample = X.iloc[0].tolist()
print(f"\\nSample prediction for {sample}: {predict(sample)}")'''
    
    def _main_block(self, project_name: str) -> str:
        return f'''if __name__ == "__main__":
    print("=" * 50)
    print("  {project_name} - Genesis AI Pipeline")
    print("=" * 50)
    print("Ready to run! Use: python pipeline.py")'''
    
    def _detect_task_type(self, description: str) -> str:
        d = description.lower()
        if any(w in d for w in ["классифик", "classif", "категор", "отток", "churn"]):
            return "classification"
        if any(w in d for w in ["регресс", "regression", "цен", "price", "прогноз"]):
            return "regression"
        return "classification"
    
    def _detect_target(self, description: str) -> Optional[str]:
        import re
        patterns = [
            r"(?:предска(?:зать|жи)|таргет|целевая|target|predict)\s+(\w+)",
            r"(?:колонк[уа]|столбец)\s+(\w+)",
        ]
        for p in patterns:
            m = re.search(p, description, re.IGNORECASE)
            if m: return m.group(1)
        return None
    
    def save_code(self, code: str, filename: str = None):
        """Сохраняет сгенерированный код в файл."""
        path = filename or f"generated_pipeline_{datetime.now().strftime('%Y%m%d_%H%M%S')}.py"
        os.makedirs("generated", exist_ok=True)
        full_path = f"generated/{path}"
        with open(full_path, "w", encoding="utf-8") as f:
            f.write(code)
        return full_path
